#
# Copyright (c) 2024 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_HEAP_MEM_POOL_SIZE=4096

CONFIG_NRF_RPC=y
CONFIG_NRF_RPC_CBOR=y
CONFIG_NRF_RPC_ZCBOR_BACKUPS=1
CONFIG_NRF_RPC_THREAD_STACK_SIZE=4096
CONFIG_NRF_RPC_GROUP_INIT_WAIT_TIME=-1

CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_NRF_RPC_UART_TRANSPORT=y
# CONFIG_NRF_RPC_IPC_SERVICE is not set
CONFIG_NRF_RPC_CBKPROXY_OUT_SLOTS=0

CONFIG_NRF_RPC_UTILS=y
CONFIG_NRF_RPC_UTILS_SERVER=y

CONFIG_SHELL=y
CONFIG_SHELL_STACK_SIZE=3072
# CONFIG_SHELL_BACKEND_SERIAL is not set
CONFIG_SHELL_BACKEND_RTT=y
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_FUNC_NAME_PREFIX_DBG=n
CONFIG_LOG_BACKEND_RTT=n
CONFIG_SHELL_LOG_BACKEND=y

# Native sim doesn't need flash/settings for this demo
# CONFIG_SETTINGS is not set
# CONFIG_FLASH is not set
# CONFIG_FLASH_MAP is not set

CONFIG_LOG_BUFFER_SIZE=21000
CONFIG_NRF_RPC_LOG_LEVEL_DBG=y
CONFIG_NRF_RPC_TR_LOG_LEVEL_DBG=y
CONFIG_NRF_RPC_OS_LOG_LEVEL_DBG=y
CONFIG_NRF_RPC_CBOR_LOG_LEVEL_DBG=y
